.github/workflows/workflow.yml
@@ -15,6 +15,10 @@ jobs:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
        
          python app.py --token $HUGGING_FACE_TOKEN
          python /mount/src/stock_analytics/llm.py --token $HUGGING_FACE_TOKEN
