name: Hugging Face API Workflow

on:
  push:
    branches:
      - main

jobs:
  hugging-face-api:
    runs-on: ubuntu-latest
    env:
      HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: |
          python app.py
