name: Hugging Face API Workflow

on:
  push:
    branches:
      - main

jobs:
  hugging-face-api:
    runs-on: ubuntu-latest
    env:
      HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variable
        run: |
          echo "HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}" >> $GITHUB_ENV

      - name: Run Python script
        run: |
          python /mount/src/stock_analytics/llm.py
